/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.DBClasses.DB;
import Backend.DBClasses.dbManager;
import Backend.Gameplay.Game;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kairav
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public static String sortingStat = "username";
    public static String order = "asc";

    public HomeScreen() throws SQLException, ClassNotFoundException {
        initComponents();
        ImageIcon pic = new ImageIcon("Cards\\logo.png");
        this.setIconImage(pic.getImage());
        setLocationRelativeTo(null);
        statButton.setText("Username");
        //connexts to the database
        connect();
        //retrieves the players and displays it on the leaderboard in ascending order
        populateComboBoxes();
        StatTable.setModel(dbManager.fetchTable(order, sortingStat, usernamejTextField.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        MainScreen = new javax.swing.JTabbedPane();
        HomePane = new javax.swing.JPanel();
        AccountPane = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        TitleSignUpLabel2 = new javax.swing.JLabel();
        uNamejLabel1 = new javax.swing.JLabel();
        passwordjLabel1 = new javax.swing.JLabel();
        uNamejTextField1 = new javax.swing.JTextField();
        passwordjTextField1 = new javax.swing.JTextField();
        loginjButton = new javax.swing.JButton();
        SignUpPanel = new javax.swing.JPanel();
        TitleSignUpLabel1 = new javax.swing.JLabel();
        fNamejLabel = new javax.swing.JLabel();
        sNamejLabel = new javax.swing.JLabel();
        uNamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        sNamejTextField = new javax.swing.JTextField();
        uNamejTextFieldSignUp = new javax.swing.JTextField();
        passwordjTextFieldSignUp = new javax.swing.JTextField();
        SignUpjButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        LeaderboardPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatTable = new javax.swing.JTable();
        Title = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        statButton = new javax.swing.JButton();
        jLabelSortBy = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        searchjButton1 = new javax.swing.JButton();
        GamePanel = new javax.swing.JPanel();
        GamejButton = new javax.swing.JButton();
        TitlejLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jLabelP2 = new javax.swing.JLabel();
        jLabelP3 = new javax.swing.JLabel();
        jLabelP4 = new javax.swing.JLabel();
        jComboBoxP1 = new javax.swing.JComboBox<>();
        jComboBoxP2 = new javax.swing.JComboBox<>();
        jComboBoxP3 = new javax.swing.JComboBox<>();
        jComboBoxP4 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LoginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TitleSignUpLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TitleSignUpLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleSignUpLabel2.setText("Login");

        uNamejLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        uNamejLabel1.setText("Username:");

        passwordjLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passwordjLabel1.setText("Password:");

        uNamejTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        passwordjTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        loginjButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        loginjButton.setText("Login");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleSignUpLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uNamejLabel1)
                    .addComponent(passwordjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uNamejTextField1)
                    .addComponent(passwordjTextField1)
                    .addComponent(loginjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleSignUpLabel2)
                .addGap(63, 63, 63)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNamejLabel1))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordjLabel1)
                    .addComponent(passwordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(loginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AccountPane.addTab("Login", LoginPanel);

        TitleSignUpLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TitleSignUpLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleSignUpLabel1.setText("Sign Up");

        fNamejLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fNamejLabel.setText("Firstname:");

        sNamejLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sNamejLabel.setText("Surname:");

        uNamejLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        uNamejLabel.setText("Username:");

        passwordjLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passwordjLabel.setText("Password:");

        fNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        sNamejTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        uNamejTextFieldSignUp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        passwordjTextFieldSignUp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        SignUpjButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SignUpjButton.setText("Sign Up");
        SignUpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleSignUpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uNamejLabel)
                    .addComponent(passwordjLabel)
                    .addComponent(sNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sNamejTextField)
                    .addComponent(fNameTextField)
                    .addComponent(uNamejTextFieldSignUp)
                    .addComponent(passwordjTextFieldSignUp)
                    .addComponent(SignUpjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleSignUpLabel1)
                .addGap(48, 48, 48)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNamejLabel)
                    .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sNamejLabel)
                    .addComponent(sNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNamejLabel)
                    .addComponent(uNamejTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordjLabel)
                    .addComponent(passwordjTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SignUpjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AccountPane.addTab("Sign Up", SignUpPanel);

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setText("X");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePaneLayout = new javax.swing.GroupLayout(HomePane);
        HomePane.setLayout(HomePaneLayout);
        HomePaneLayout.setHorizontalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePaneLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(AccountPane, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(backButton))
        );
        HomePaneLayout.setVerticalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AccountPane, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainScreen.addTab("Home", HomePane);

        LeaderboardPane.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        StatTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        StatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Games Played", "Wins", "Losses", "Hands", "Hands Won", "Total Points", "Games Terminated"
            }
        ));
        StatTable.setGridColor(new java.awt.Color(102, 102, 102));
        StatTable.setShowGrid(true);
        jScrollPane1.setViewportView(StatTable);

        Title.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Player Statistics Table");

        orderButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        orderButton.setText("Ascending Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        statButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        statButton.setText("Wins");
        statButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButtonActionPerformed(evt);
            }
        });

        jLabelSortBy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSortBy.setText("Sort By:");

        usernamejTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabelUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUsername.setText("Username:");

        refreshButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        searchjButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchjButton1.setText("Search");
        searchjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeaderboardPaneLayout = new javax.swing.GroupLayout(LeaderboardPane);
        LeaderboardPane.setLayout(LeaderboardPaneLayout);
        LeaderboardPaneLayout.setHorizontalGroup(
            LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaderboardPaneLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderboardPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderboardPaneLayout.createSequentialGroup()
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabelSortBy)
                        .addGap(43, 43, 43)
                        .addComponent(statButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderboardPaneLayout.createSequentialGroup()
                        .addComponent(jLabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(542, 542, 542))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderboardPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
            .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaderboardPaneLayout.createSequentialGroup()
                    .addContainerGap(601, Short.MAX_VALUE)
                    .addComponent(searchjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(351, 351, 351)))
        );
        LeaderboardPaneLayout.setVerticalGroup(
            LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaderboardPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(refreshButton))
                .addGap(37, 37, 37)
                .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSortBy))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(LeaderboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeaderboardPaneLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(searchjButton1)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        MainScreen.addTab("Player Statistics", LeaderboardPane);

        GamejButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        GamejButton.setText("Start Game");
        GamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamejButtonActionPerformed(evt);
            }
        });

        TitlejLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TitlejLabel.setText("ThUNEE");

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kairav\\OneDrive\\Documents\\NetBeansProjects\\ThuneeBasic\\Cards\\logo.png")); // NOI18N

        jLabelP1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelP1.setText("Player 1");

        jLabelP2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelP2.setText("Player 2");

        jLabelP3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelP3.setText("Player 3");

        jLabelP4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelP4.setText("Player 4");

        jComboBoxP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***" }));

        jComboBoxP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***" }));

        jComboBoxP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***" }));

        jComboBoxP4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***" }));

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlejLabel)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxP1, 0, 100, Short.MAX_VALUE)
                            .addComponent(jComboBoxP2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxP3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxP4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel)
                .addGap(18, 18, 18)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelP1)
                            .addComponent(jComboBoxP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelP2)
                            .addComponent(jComboBoxP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelP3)
                            .addComponent(jComboBoxP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelP4)
                            .addComponent(jComboBoxP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(GamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        MainScreen.addTab("Game", GamePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainScreen)
                .addContainerGap())
        );

        MainScreen.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        //checks the current order the leaderboard is being sorted in and changes it to the opposite order
        try {
            changeOrder();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");
        }

    }//GEN-LAST:event_orderButtonActionPerformed

    private void SignUpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpjButtonActionPerformed
        // TODO add your handling code here:

        String name = fNameTextField.getText() + " " + sNamejTextField.getText();
        String pass = passwordjTextFieldSignUp.getText();
        String user = uNamejTextFieldSignUp.getText();
        try {
            if (dbManager.isUser(user) || user.contains("*")) {
                JOptionPane.showMessageDialog(rootPane, "This username is already taken or contains an invalid character");
                uNamejTextFieldSignUp.setText("");
            } else {
                dbManager.createUser(name, pass, user);
                showAccountScreen(user);
                populateComboBoxes();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");
        }

    }//GEN-LAST:event_SignUpjButtonActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        // TODO add your handling code here:
        String pass = passwordjTextField1.getText();
        String user = uNamejTextField1.getText();
        try {
            if (dbManager.isvalidUser(user, pass)) {
                showAccountScreen(user);
            } else {
                JOptionPane.showMessageDialog(rootPane, "This username and/or password is incorrect");
                passwordjTextField1.setText("");
                uNamejTextField1.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");
        }

    }//GEN-LAST:event_loginjButtonActionPerformed

    private void GamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamejButtonActionPerformed
        // TODO add your handling code here:
        String p1 = jComboBoxP1.getSelectedItem().toString();
        String p2 = jComboBoxP2.getSelectedItem().toString();
        String p3 = jComboBoxP3.getSelectedItem().toString();
        String p4 = jComboBoxP4.getSelectedItem().toString();
        if (!(p1.contains("*") || p2.contains("*") || p3.contains("*") || p4.contains("*")
                || p1.equals(p2) || p1.equals(p3) || p1.equals(p4)
                || p2.equals(p3) || p2.equals(p4) || p3.equals(p4))) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        try {
                            Game g = new Game(p1, p2, p3, p4);
                            new GameScreen(g).setVisible(true);
                        } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(null, "Couldn't find the DB driver");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Couldn't connect to the database");
                    }
                }
            });
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select four different players");
        }
    }//GEN-LAST:event_GamejButtonActionPerformed


    private void statButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButtonActionPerformed
        // TODO add your handling code here:

        try {
            changeStat();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");
        }
    }//GEN-LAST:event_statButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try {
            StatTable.setModel(dbManager.fetchTable(order, sortingStat, usernamejTextField.getText()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");

        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomeScreen().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Could not find DB driver");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Could not connect to the DB");
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AccountPane;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JButton GamejButton;
    private javax.swing.JPanel HomePane;
    private javax.swing.JPanel LeaderboardPane;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JTabbedPane MainScreen;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JButton SignUpjButton;
    private javax.swing.JTable StatTable;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleSignUpLabel1;
    private javax.swing.JLabel TitleSignUpLabel2;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JLabel fNamejLabel;
    private javax.swing.JComboBox<String> jComboBoxP1;
    private javax.swing.JComboBox<String> jComboBoxP2;
    private javax.swing.JComboBox<String> jComboBoxP3;
    private javax.swing.JComboBox<String> jComboBoxP4;
    private javax.swing.JLabel jLabelP1;
    private javax.swing.JLabel jLabelP2;
    private javax.swing.JLabel jLabelP3;
    private javax.swing.JLabel jLabelP4;
    private javax.swing.JLabel jLabelSortBy;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton loginjButton;
    private javax.swing.JLabel logo;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel passwordjLabel1;
    private javax.swing.JTextField passwordjTextField1;
    private javax.swing.JTextField passwordjTextFieldSignUp;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel sNamejLabel;
    private javax.swing.JTextField sNamejTextField;
    private javax.swing.JButton searchjButton1;
    private javax.swing.JButton statButton;
    private javax.swing.JLabel uNamejLabel;
    private javax.swing.JLabel uNamejLabel1;
    private javax.swing.JTextField uNamejTextField1;
    private javax.swing.JTextField uNamejTextFieldSignUp;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables

    public void populateComboBoxes() {
        try {
            for (String user : dbManager.getAllUsers()) {
                if (user != null) { // Ensure the username is not null
                    jComboBoxP1.addItem(user);
                    jComboBoxP2.addItem(user);
                    jComboBoxP3.addItem(user);
                    jComboBoxP4.addItem(user);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Failed to connect to the DB");
        }
    }

    //changes the order the leaders are displayed in
    public void changeOrder() throws SQLException {
        if (order.equals("asc")) {
            order = "desc";
            orderButton.setText("Descending Order");
        } else {
            order = "asc";
            orderButton.setText("Ascending Order");
        }
        StatTable.setModel(dbManager.fetchTable(order, sortingStat, usernamejTextField.getText()));

    }
    //changes the stat used to sort the order the leaders are displayed in

    public void changeStat() throws SQLException {
        if (sortingStat.equals("username")) {
            sortingStat = "numGames";
            statButton.setText("Games Played");
        } else if (sortingStat.equals("numGames")) {
            sortingStat = "numWins";
            statButton.setText("Games Won");
        } else if (sortingStat.equals("numWins")) {
            sortingStat = "numLosses";
            statButton.setText("Games Lost");
        } else if (sortingStat.equals("numLosses")) {
            sortingStat = "totalHands";
            statButton.setText("Hands Played");
        } else if (sortingStat.equals("totalHands")) {
            sortingStat = "handsWon";
            statButton.setText("Hands Won");
        } else if (sortingStat.equals("handsWon")) {
            sortingStat = "totalPoints";
            statButton.setText("Points Won");
        } else if (sortingStat.equals("totalPoints")) {
            sortingStat = "gamesTerminated";
            statButton.setText("Games Terminated");
        } else if (sortingStat.equals("gamesTerminated")) {
            sortingStat = "username";
            statButton.setText("Username");
        }
        StatTable.setModel(dbManager.fetchTable(order, sortingStat, usernamejTextField.getText()));

    }

    public static void connect() {
        try {
            DB.init();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Could not find DB driver");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Could not connect to the DB");
        }
    }

    public static void showAccountScreen(String user) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountScreen(user).setVisible(true);
            }
        });
    }
}
